services:
  - type: web
    name: financial-doc-qa
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port $PORT --server.enableCORS false --server.enableXsrfProtection false"
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: HUGGINGFACEHUB_API_TOKEN
        sync: false
    pythonVersion: 3.11.9